export { default as IconTarget }   from './IconTarget'
export { default as IconChart }    from './IconChart'
export { default as IconBook }     from './IconBook'
export { default as IconFlame }    from './IconFlame'
export { default as IconAtom }     from './IconAtom'
export { default as IconFlask }    from './IconFlask'
export { default as IconSigma }    from './IconSigma'
export { default as IconClock }    from './IconClock'
export { default as IconCalendar } from './IconCalendar'
export { default as IconBell }     from './IconBell'
export { default as IconUser }     from './IconUser'
export { default as IconLock }     from './IconLock'
export { default as IconTrophy }   from './IconTrophy'
export { default as IconTrend }    from './IconTrend'
export { default as IconWarning }  from './IconWarning'
export { default as IconCheck }    from './IconCheck'
export { default as IconLogout }   from './IconLogout'
export { default as IconPlus }     from './IconPlus'
export { default as IconArrow }    from './IconArrow'
export { default as IconDashboard} from './IconDashboard'
export { default as IconBatch }    from './IconBatch'
export { default as IconSearch }   from './IconSearch'
export { default as IconTrash }    from './IconTrash'
export { default as IconX }        from './IconX'
export { default as IconInfo }     from './IconInfo'
export { default as IconSort }     from './IconSort'
export { default as IconArrowRight} from './IconArrowRight'
export { default as IconLoader }    from './IconLoader'
export { default as IconUsers }     from './IconUsers'
export { default as IconCreditCard} from './IconCreditCard'
export { default as IconLayoutDashboard } from './IconLayoutDashboard'
export { default as IconAlertCircle } from './IconAlertCircle'
export { default as IconFilter }    from './IconFilter'
export { default as IconArrowUpRight } from './IconArrowUpRight'
export { default as IconCircleMinus } from './IconCircleMinus'
export { default as IconEye }       from './IconEye'
export { default as IconTeacher }   from './IconTeacher'
export { default as IconStudent }   from './IconStudent'
export { default as IconPower }     from './IconPower'
export { default as IconArrowLeft } from './IconArrowLeft'
export { default as IconFileExport} from './IconFileExport'
export { default as IconDownload }  from './IconDownload'
export { default as IconRocket }    from './IconRocket'
export { default as IconShield }    from './IconShield'
export { default as IconEdit }      from './IconEdit'
export { default as IconKey }       from './IconKey'
